"""Literature review paragraphs for Article 1 (humanised Q1 style)."""

SEC_21 = [
    (
        "Most working definitions still treat sport tourism as travel generated by "
        "watching, participating in, or visiting places associated with sport "
        "(Higham & Hinch, 2018). That sounds tidy on paper. In practice the category "
        "leaks in useful ways: a marathon weekend is also a hospitality product; a "
        "stadium tour is heritage consumption; a youth tournament can be family tourism "
        "with a competitive spine. Getz and Page (2016) argued that event tourism "
        "research matured by taking those overlaps seriously rather than policing "
        "disciplinary borders. Sport tourism scholarship has followed a similar path, "
        "moving from early definitional disputes toward questions of development, "
        "place and impact (Weed, 2009; Hinch & Higham, 2011)."
    ),
    (
        "What makes the setting fertile for innovation research is precisely this "
        "hybridity. Destinations do not innovate “tourism” or “sport” in isolation; "
        "they assemble packages of mobility, competition, spectacle and local service "
        "supply. Arici et al. (2025) show that contemporary sport-tourism writing "
        "clusters around tourist behaviour, sustainable and economic development, "
        "events and destination image, and longer active-travel careers. Innovation, "
        "in that landscape, can mean a new event product, a redesigned visitor journey, "
        "a digitally mediated fan experience, or a governance tweak that changes who "
        "captures value. The literature is rich on outcomes and motivations. It is "
        "thinner on how innovative and entrepreneurial vocabularies are organised when "
        "sport tourism is the explicit context."
    ),
]

SEC_22 = [
    (
        "Sport entrepreneurship research grew out of a dissatisfaction with importing "
        "generic start-up templates into clubs, federations and event firms. Ratten "
        "(2012, 2018) pushed the field toward a broader reading: entrepreneurship as "
        "opportunity recognition, resource recombination and cultural change inside "
        "sport systems, including social and community ventures. That framing travels "
        "well into tourism because many sport-tourism businesses are small, seasonal "
        "and lifestyle-driven rather than scaled platform firms (Ivanycheva et al., 2024). "
        "Surf camps, trail-running series, boutique event agencies and athlete-led "
        "tour products often look more like lifestyle entrepreneurship than classic "
        "Schumpeterian disruption."
    ),
    (
        "Empirical work in developing-country sport tourism makes the same point from "
        "another angle. Heydari et al. (2022) show how entrepreneurial behaviours are "
        "adopted under institutional constraints that differ sharply from mature "
        "destination economies. González-Serrano et al. (2020), mapping sustainable "
        "sport entrepreneurship and innovation, likewise found mega-event sustainability "
        "and inclusion-oriented innovation as developed pockets, while urging more "
        "work that joins tourism, entrepreneurship and environmental concerns. Taken "
        "together, these studies suggest entrepreneurship in sport tourism is less a "
        "single construct than a family of practices: commercial venturing, social "
        "value creation, and institutional entrepreneurship around events and places. "
        "A concept-level map is useful precisely because those practices share language "
        "without sharing the same intellectual neighbourhood."
    ),
]

SEC_23 = [
    (
        "Digitalisation has become difficult to treat as a side theme. Stadium "
        "connectivity, streaming, virtual and augmented overlays, data-driven "
        "operations and blockchain experiments now appear routinely in sport-event "
        "and tourism-event writing (Thelen & Kim, 2024). Fans are no longer only "
        "bodies in seats; they are nodes in a mediated experience economy. For "
        "destinations, that shifts innovation talk toward platforms and infrastructures "
        "as much as toward product design. At the same time, sustainability pressures—"
        "carbon accounting, greener logistics, urban host-city narratives—have moved "
        "from peripheral CSR language toward core event strategy (González-Serrano "
        "et al., 2020; Gössling et al., 2021). The so-called twin agenda of digital "
        "and green transformation is visible even when papers do not use that label."
    ),
    (
        "Mega-events and Olympic hosting remain a specialised but influential arena "
        "inside this conversation. Legacy, leverage and destination imaging have long "
        "histories (Preuss, 2007; Chalip, 2006; Getz & Page, 2016), yet recent work "
        "increasingly ties those debates to green branding, urban transformation and "
        "reputational risk. Smaller events, by contrast, are often discussed as more "
        "embeddable in local economies and communities (Rossini et al., 2024). The "
        "result is a literature that can sound unified under “sport events” while "
        "actually splitting between high-visibility hosting politics and more ordinary "
        "entrepreneurial event making. Any serious mapping of innovation and "
        "entrepreneurship has to keep that split in view rather than dissolving it "
        "into a single event cluster."
    ),
]

SEC_24 = [
    (
        "Bibliometric and science-mapping methods are now common in tourism and sport "
        "management, partly because the publication base has become too large for "
        "narrative review alone (Donthu et al., 2021; Hammerschmidt et al., 2024; "
        "Arici et al., 2025). Performance analysis tells us who publishes and where; "
        "science mapping asks how knowledge is structured. Co-word and concept-network "
        "approaches, tracing back to Callon et al. (1983), assume that terms co-occurring "
        "in titles, abstracts and keywords signal conceptual proximity. Visualisation "
        "tools and similarity normalisations refined that intuition for large corpora "
        "(van Eck & Waltman, 2009, 2014). Topic models add a complementary cut: instead "
        "of only pairwise association, they recover mixtures of themes across documents "
        "(Lee & Seung, 1999; O’Callaghan et al., 2015)."
    ),
    (
        "For the present study, the methodological bet is modest but deliberate. "
        "TF–IDF identifies salient vocabulary; NMF recovers interpretable topics in a "
        "mid-sized specialised corpus; a Jaccard-weighted concept network with Louvain "
        "communities and betweenness centrality highlights bridges (Blondel et al., 2008; "
        "Freeman, 1978; Burt, 2004). We do not treat the network as a causal model of "
        "the industry. We treat it as a disciplined reading of how the literature "
        "connects its own concepts. That is enough, we argue, to move from a list of "
        "popular keywords to a structured account of intellectual neighbourhoods and "
        "the terms that travel between them."
    ),
]

SEC_25 = [
    (
        "The conceptual premise of the paper follows from the review above. Sport "
        "tourism and sport events provide the empirical platform; innovation and "
        "entrepreneurship supply the focal vocabularies; digitalisation and "
        "sustainability act as contemporary cross-cutting pressures; science-mapping "
        "tools supply the analytical lens. We expect the published field to be "
        "multi-core rather than unidimensional—destination markets, entrepreneurial "
        "ventures, digital infrastructures, green transition and mega-event hosting "
        "are unlikely to collapse into one topic. We also expect integrative work to "
        "be done by a smaller set of bridging concepts, most likely managerial and "
        "developmental terms that appear across specialised communities. The empirical "
        "sections test those expectations against the Scopus corpus."
    ),
]
